## **NumPy**
*Ngày 6 tháng 7 năm 2024*



### **Exercise 1: Basic NumPy**


In [1]:
# Question 1:
import numpy as np
arr = np.arange(0, 10, 1)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
# Question 2:
arr1 = np.ones((3, 3)) > 0
arr2 = np.ones((3,3), dtype=bool)
arr3 = np.full((3,3), fill_value=True, dtype=bool)
print(arr1, '\n', arr2, '\n', arr3)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]] 
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]] 
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [3]:
# Question 3:
import numpy as np
arr = np.arange(0, 10)
print(arr[arr % 2 == 1])

[1 3 5 7 9]


In [4]:
# Question 4:
import numpy as np
arr = np.arange(0, 10)
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [5]:
# Question 5:
import numpy as np
arr = np.arange(10)
arr_2d = arr.reshape(2, -1)
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [6]:
# Question 6:
import numpy as np
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([arr1, arr2], axis=0)
print("Result:\n", c)

Result:
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [7]:
# Question 7:
import numpy as np
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([arr1, arr2], axis=1)
print("C =", c)

C = [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [8]:
# Question 8:
import numpy as np
arr = np.array([1, 2, 3])
print(np.repeat(arr, 3))
print(np.tile(arr, 3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [9]:
# Question 9:
import numpy as np
a = np.array([2, 6, 1, 9, 10, 3, 27])
index = np.where((a >= 5) & (a <= 10))
print("result", a[index])

result [ 6  9 10]


In [10]:
# Question 10:
import numpy as np

def maxx(x, y):
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max = np.vectorize(maxx, otypes=[float])
print(pair_max(a, b))

[6. 7. 9. 8. 9. 7. 5.]


In [11]:
# Question 11:
import numpy as np

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

print("Result", np.where(a < b, b, a))

Result [6 7 9 8 9 7 5]


## Exercise 2: Image Processing

In [12]:
import matplotlib.image as mpimg
import numpy as np

img = mpimg.imread('dog.jpeg')

In [13]:
# Question 12:
gray_img_01 = (np.max(img, axis=2) + np.min(img, axis=2)) / 2
print(gray_img_01[0, 0])

102.5


In [14]:
# Question 13:
gray_img_02 = np.mean(img, axis=2)
print(gray_img_02[0, 0])

107.66666666666667


In [15]:
# Question 14:
gray_img_03 = 0.21 * img[:,:,0] + 0.72 * img[:,:,1] + 0.07 * img[:,:,2]
print(gray_img_03[0, 0])

126.22999999999999


## Exercise 3: Tabular Data Analysis

In [16]:
import pandas as pd
import numpy as np

df = pd.read_csv('advertising.csv')
data = df.to_numpy()

In [17]:
# Question 15:
max_sales = np.max(data[:, -1])
max_index = np.argmax(data[:, -1])
print(f"Max: {max_sales} - Index: {max_index}")

Max: 27.0 - Index: 175


In [18]:
# Question 16:
tv_mean = np.mean(data[:, 0])
print(f"{tv_mean:.1f}")

147.0


In [19]:
# Question 17:
count = np.sum(data[:, -1] >= 20)
print(count)

40


In [20]:
# Question 18:
radio_mean = np.mean(data[data[:, -1] >= 15, 1])
print(f"{radio_mean:.1f}")

26.2


In [21]:
# Question 19:
newspaper_mean = np.mean(data[:, 2])
total_sales = np.sum(data[data[:, 2] > newspaper_mean, -1])
print(f"{total_sales:.1f}")

1405.1


In [ ]:
# Question 20:
sales_mean = np.mean(data[:, -1])
scores = np.where(data[:, -1] > sales_mean, 'Good', np.where(data[:, -1] < sales_mean, 'Bad', 'Average'))
# Question 7:print(scores[7:10])

In [23]:
# Question 21:
sales_mean = np.mean(data[:, -1])
closest_to_mean = data[np.argmin(np.abs(data[:, -1] - sales_mean)), -1]
scores = np.where(data[:, -1] > closest_to_mean, 'Good', np.where(data[:, -1] < closest_to_mean, 'Bad', 'Average'))
print(scores[7:10])

['Bad' 'Bad' 'Good']
